; Generated by cc64 from forward.c
; Assemble with: c64asm forward.asm -o program.prg
 
; ---- zero page pseudo-registers -------------------------------
__zpSP  = $02     ; soft operand-stack pointer (2 bytes)
__zpAP  = $F3     ; effective-address pointer (2 bytes)
__zpAP2 = $F5     ; saved-AP scratch, used across RHS evaluation of
                  ; assignments/compound-assignments to array elements (2 bytes)
__zpT1 = $F7      ; runtime scratch (2 bytes)
__zpT0 = $F9      ; runtime scratch (2 bytes)
__zpR  = $FB      ; primary register / return value (2 bytes)
__zpR2 = $FD      ; secondary operand register (2 bytes)
__CHROUT = $FFD2
 
.basic
    LDA #14           ; switch to the lower/upper character set - required
    JSR __CHROUT      ; for the PETSCII case mapping below to render as letters
                      ; (the default charset only has graphics past $C0)
    LDA #<__rt_stack
    STA __zpSP
    LDA #>__rt_stack
    STA __zpSP+1
    JSR __fn_main
    RTS
 
; ---- runtime library -------------------------------------------
__rt_push:
    LDY #0
    LDA __zpR
    STA (__zpSP),Y
    INY
    LDA __zpR+1
    STA (__zpSP),Y
    CLC
    LDA __zpSP
    ADC #2
    STA __zpSP
    LDA __zpSP+1
    ADC #0
    STA __zpSP+1
    RTS
 
__rt_pop2:
    SEC
    LDA __zpSP
    SBC #2
    STA __zpSP
    LDA __zpSP+1
    SBC #0
    STA __zpSP+1
    LDY #0
    LDA (__zpSP),Y
    STA __zpR2
    INY
    LDA (__zpSP),Y
    STA __zpR2+1
    RTS
 
__rt_mul16:
    LDA #0
    STA __zpT0
    STA __zpT0+1
    LDX #16
__rt_mul16_loop:
    LSR __zpR+1
    ROR __zpR
    BCC __rt_mul16_noadd
    CLC
    LDA __zpT0
    ADC __zpR2
    STA __zpT0
    LDA __zpT0+1
    ADC __zpR2+1
    STA __zpT0+1
__rt_mul16_noadd:
    ASL __zpR2
    ROL __zpR2+1
    DEX
    BNE __rt_mul16_loop
    LDA __zpT0
    STA __zpR
    LDA __zpT0+1
    STA __zpR+1
    RTS
 
__rt_udiv16:
    LDA #0
    STA __zpT0
    STA __zpT0+1
    LDX #16
__rt_udiv16_loop:
    ASL __zpR2
    ROL __zpR2+1
    ROL __zpT0
    ROL __zpT0+1
    LDA __zpT0
    SEC
    SBC __zpR
    TAY
    LDA __zpT0+1
    SBC __zpR+1
    BCC __rt_udiv16_skip
    STA __zpT0+1
    STY __zpT0
    INC __zpR2
__rt_udiv16_skip:
    DEX
    BNE __rt_udiv16_loop
    RTS
 
__rt_neg_r2:
    SEC
    LDA #0
    SBC __zpR2
    TAX
    LDA #0
    SBC __zpR2+1
    STA __zpR2+1
    STX __zpR2
    RTS
 
__rt_neg_r:
    SEC
    LDA #0
    SBC __zpR
    TAX
    LDA #0
    SBC __zpR+1
    STA __zpR+1
    STX __zpR
    RTS
 
__rt_neg_t0:
    SEC
    LDA #0
    SBC __zpT0
    TAX
    LDA #0
    SBC __zpT0+1
    STA __zpT0+1
    STX __zpT0
    RTS
 
__rt_sdivmod16:
    LDA #0
    STA __zpT1
    STA __zpT1+1
    LDA __zpR2+1
    BPL __rt_sdm_d1
    JSR __rt_neg_r2
    INC __zpT1
__rt_sdm_d1:
    LDA __zpR+1
    BPL __rt_sdm_d2
    JSR __rt_neg_r
    INC __zpT1+1
__rt_sdm_d2:
    JSR __rt_udiv16
    LDA __zpT1
    EOR __zpT1+1
    AND #1
    BEQ __rt_sdm_qdone
    JSR __rt_neg_r2
__rt_sdm_qdone:
    LDA __zpT1
    BEQ __rt_sdm_rdone
    JSR __rt_neg_t0
__rt_sdm_rdone:
    RTS
 
__rt_eq16:
    LDA __zpR2
    CMP __zpR
    BNE __rt_eq16_ne
    LDA __zpR2+1
    CMP __zpR+1
    BNE __rt_eq16_ne
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
__rt_eq16_ne:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
 
__rt_ne16:
    LDA __zpR2
    CMP __zpR
    BNE __rt_ne16_ne
    LDA __zpR2+1
    CMP __zpR+1
    BNE __rt_ne16_ne
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ne16_ne:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_sub_r2r:
    SEC
    LDA __zpR2
    SBC __zpR
    LDA __zpR2+1
    SBC __zpR+1
    BVC __rt_sub_r2r_ok
    EOR #$80
__rt_sub_r2r_ok:
    RTS
 
__rt_sub_rr2:
    SEC
    LDA __zpR
    SBC __zpR2
    LDA __zpR+1
    SBC __zpR2+1
    BVC __rt_sub_rr2_ok
    EOR #$80
__rt_sub_rr2_ok:
    RTS
 
__rt_lt16:
    JSR __rt_sub_r2r
    BMI __rt_lt16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_lt16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_ge16:
    JSR __rt_sub_r2r
    BPL __rt_ge16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ge16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_gt16:
    JSR __rt_sub_rr2
    BMI __rt_gt16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_gt16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_le16:
    JSR __rt_sub_rr2
    BPL __rt_le16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_le16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_shl16:
    LDX __zpR
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
__rt_shl16_loop:
    CPX #0
    BEQ __rt_shl16_done
    ASL __zpR
    ROL __zpR+1
    DEX
    JMP __rt_shl16_loop
__rt_shl16_done:
    RTS
 
__rt_shr16:
    LDX __zpR
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
__rt_shr16_loop:
    CPX #0
    BEQ __rt_shr16_done
    LDA __zpR+1
    CMP #$80
    ROR __zpR+1
    ROR __zpR
    DEX
    JMP __rt_shr16_loop
__rt_shr16_done:
    RTS
 
__rt_topetscii:
    LDA __zpR
    CMP #$61
    BCC __rt_tp_notlower
    CMP #$7B
    BCS __rt_tp_notlower
    SEC
    SBC #$20
    STA __zpR
    JMP __rt_tp_done
__rt_tp_notlower:
    CMP #$41
    BCC __rt_tp_done
    CMP #$5B
    BCS __rt_tp_done
    CLC
    ADC #$80
    STA __zpR
__rt_tp_done:
    RTS
 
; ---- global variables --------------------------------------------
__g_g_flag:
    .byte 1
__g_g_neg:
    .word -5
 
; ---- function caller_calls_later ---------------------------------------------
__fn_caller_calls_later_v_x:
    .fill 2, 0
__fn_caller_calls_later:
    LDA __fn_caller_calls_later_v_x
    STA __zpR
    LDA __fn_caller_calls_later_v_x+1
    STA __zpR+1
    LDA __zpR
    STA __fn_later_defined_v_x
    LDA __zpR+1
    STA __fn_later_defined_v_x+1
    JSR __fn_later_defined
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    RTS
    RTS
 
; ---- function later_defined ---------------------------------------------
__fn_later_defined_v_x:
    .fill 2, 0
__fn_later_defined:
    LDA __fn_later_defined_v_x
    STA __zpR
    LDA __fn_later_defined_v_x+1
    STA __zpR+1
    JSR __rt_push
    LDA #<2
    STA __zpR
    LDA #>2
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    RTS
    RTS
 
; ---- function earlier_defined ---------------------------------------------
__fn_earlier_defined_v_x:
    .fill 2, 0
__fn_earlier_defined:
    LDA __fn_earlier_defined_v_x
    STA __zpR
    LDA __fn_earlier_defined_v_x+1
    STA __zpR+1
    JSR __rt_push
    LDA #<100
    STA __zpR
    LDA #>100
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    RTS
    RTS
 
; ---- function caller_calls_earlier ---------------------------------------------
__fn_caller_calls_earlier_v_x:
    .fill 2, 0
__fn_caller_calls_earlier:
    LDA __fn_caller_calls_earlier_v_x
    STA __zpR
    LDA __fn_caller_calls_earlier_v_x+1
    STA __zpR+1
    LDA __zpR
    STA __fn_earlier_defined_v_x
    LDA __zpR+1
    STA __fn_earlier_defined_v_x+1
    JSR __fn_earlier_defined
    RTS
    RTS
 
; ---- function main ---------------------------------------------
__fn_main:
    LDA #<48
    STA __zpR
    LDA #>48
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    LDA __zpR
    STA __fn_caller_calls_later_v_x
    LDA __zpR+1
    STA __fn_caller_calls_later_v_x+1
    JSR __fn_caller_calls_later
    JSR __rt_push
    LDA #<21
    STA __zpR
    LDA #>21
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_eq16
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    LDA #<48
    STA __zpR
    LDA #>48
    STA __zpR+1
    JSR __rt_push
    LDA #<5
    STA __zpR
    LDA #>5
    STA __zpR+1
    LDA __zpR
    STA __fn_caller_calls_earlier_v_x
    LDA __zpR+1
    STA __fn_caller_calls_earlier_v_x+1
    JSR __fn_caller_calls_earlier
    JSR __rt_push
    LDA #<105
    STA __zpR
    LDA #>105
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_eq16
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    LDA #<48
    STA __zpR
    LDA #>48
    STA __zpR+1
    JSR __rt_push
    LDA __g_g_flag
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_eq16
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    LDA #<48
    STA __zpR
    LDA #>48
    STA __zpR+1
    JSR __rt_push
    LDA __g_g_neg
    STA __zpR
    LDA __g_g_neg+1
    STA __zpR+1
    JSR __rt_push
    LDA #<5
    STA __zpR
    LDA #>5
    STA __zpR+1
    SEC
    LDA #0
    SBC __zpR
    TAX
    LDA #0
    SBC __zpR+1
    STA __zpR+1
    STX __zpR
    JSR __rt_pop2
    JSR __rt_eq16
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    LDA #<13
    STA __zpR
    LDA #>13
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    RTS
 
; ---- operand stack (grows upward, 256 slots) ----------------------
__rt_stack:
    .fill 512, 0
