; Generated by cc64 from tests/pointers.c
; Assemble with: c64asm tests/pointers.asm -o program.prg
 
; ---- zero page pseudo-registers ---------------------------------
; Only $02/$03 and $FB-$FE are used here. Per the KERNAL's own
; memory map, those are the ONLY zero-page bytes confirmed genuinely
; free: $F3/$F4 is the current-line-in-color-RAM pointer (touched by
; CHROUT itself when it colors a printed character) and $F5/$F6 is the
; keyboard-matrix-to-PETSCII conversion table pointer (touched by the
; keyboard scan on every background IRQ, ~60x/sec) - both looked like
; safe 'adjacent' bytes but are not; this bit us for real once already.
__zpAP = $02      ; effective-address pointer (2 bytes) - needs zero
                  ; page because it's used with (zp),Y indirection
__zpR  = $FB      ; primary register / return value (2 bytes)
__zpR2 = $FD      ; secondary operand register (2 bytes)
__CHROUT = $FFD2
 
.basic
    LDA #14           ; switch to the lower/upper character set - required
    JSR __CHROUT      ; for the PETSCII case mapping below to render as letters
                      ; (the default charset only has graphics past $C0)
    LDA #0
    STA __rt_spidx
    JSR __fn_main
    RTS
 
; ---- runtime scratch storage (plain RAM, NOT zero page - only __zpAP
; needs (zp),Y indirection; these are always accessed directly) -------
__rt_spidx:
    .byte 0
__zpAP2:
    .fill 2, 0
__zpT1:
    .fill 2, 0
__zpT0:
    .fill 2, 0
 
; ---- runtime library -------------------------------------------
__rt_push:
    LDX __rt_spidx
    LDA __zpR
    STA __rt_stack,X
    LDA __zpR+1
    STA __rt_stack+1,X
    INX
    INX
    STX __rt_spidx
    RTS
 
__rt_pop2:
    LDX __rt_spidx
    DEX
    DEX
    LDA __rt_stack,X
    STA __zpR2
    LDA __rt_stack+1,X
    STA __zpR2+1
    STX __rt_spidx
    RTS
 
__rt_mul16:
    LDA #0
    STA __zpT0
    STA __zpT0+1
    LDX #16
__rt_mul16_loop:
    LSR __zpR+1
    ROR __zpR
    BCC __rt_mul16_noadd
    CLC
    LDA __zpT0
    ADC __zpR2
    STA __zpT0
    LDA __zpT0+1
    ADC __zpR2+1
    STA __zpT0+1
__rt_mul16_noadd:
    ASL __zpR2
    ROL __zpR2+1
    DEX
    BNE __rt_mul16_loop
    LDA __zpT0
    STA __zpR
    LDA __zpT0+1
    STA __zpR+1
    RTS
 
__rt_udiv16:
    LDA #0
    STA __zpT0
    STA __zpT0+1
    LDX #16
__rt_udiv16_loop:
    ASL __zpR2
    ROL __zpR2+1
    ROL __zpT0
    ROL __zpT0+1
    LDA __zpT0
    SEC
    SBC __zpR
    TAY
    LDA __zpT0+1
    SBC __zpR+1
    BCC __rt_udiv16_skip
    STA __zpT0+1
    STY __zpT0
    INC __zpR2
__rt_udiv16_skip:
    DEX
    BNE __rt_udiv16_loop
    RTS
 
__rt_neg_r2:
    SEC
    LDA #0
    SBC __zpR2
    TAX
    LDA #0
    SBC __zpR2+1
    STA __zpR2+1
    STX __zpR2
    RTS
 
__rt_neg_r:
    SEC
    LDA #0
    SBC __zpR
    TAX
    LDA #0
    SBC __zpR+1
    STA __zpR+1
    STX __zpR
    RTS
 
__rt_neg_t0:
    SEC
    LDA #0
    SBC __zpT0
    TAX
    LDA #0
    SBC __zpT0+1
    STA __zpT0+1
    STX __zpT0
    RTS
 
__rt_sdivmod16:
    LDA #0
    STA __zpT1
    STA __zpT1+1
    LDA __zpR2+1
    BPL __rt_sdm_d1
    JSR __rt_neg_r2
    INC __zpT1
__rt_sdm_d1:
    LDA __zpR+1
    BPL __rt_sdm_d2
    JSR __rt_neg_r
    INC __zpT1+1
__rt_sdm_d2:
    JSR __rt_udiv16
    LDA __zpT1
    EOR __zpT1+1
    AND #1
    BEQ __rt_sdm_qdone
    JSR __rt_neg_r2
__rt_sdm_qdone:
    LDA __zpT1
    BEQ __rt_sdm_rdone
    JSR __rt_neg_t0
__rt_sdm_rdone:
    RTS
 
__rt_eq16:
    LDA __zpR2
    CMP __zpR
    BNE __rt_eq16_ne
    LDA __zpR2+1
    CMP __zpR+1
    BNE __rt_eq16_ne
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
__rt_eq16_ne:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
 
__rt_ne16:
    LDA __zpR2
    CMP __zpR
    BNE __rt_ne16_ne
    LDA __zpR2+1
    CMP __zpR+1
    BNE __rt_ne16_ne
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ne16_ne:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_sub_r2r:
    SEC
    LDA __zpR2
    SBC __zpR
    LDA __zpR2+1
    SBC __zpR+1
    BVC __rt_sub_r2r_ok
    EOR #$80
__rt_sub_r2r_ok:
    RTS
 
__rt_sub_rr2:
    SEC
    LDA __zpR
    SBC __zpR2
    LDA __zpR+1
    SBC __zpR2+1
    BVC __rt_sub_rr2_ok
    EOR #$80
__rt_sub_rr2_ok:
    RTS
 
__rt_lt16:
    JSR __rt_sub_r2r
    BMI __rt_lt16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_lt16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_ge16:
    JSR __rt_sub_r2r
    BPL __rt_ge16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ge16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_gt16:
    JSR __rt_sub_rr2
    BMI __rt_gt16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_gt16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_le16:
    JSR __rt_sub_rr2
    BPL __rt_le16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_le16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_shl16:
    LDX __zpR
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
__rt_shl16_loop:
    CPX #0
    BEQ __rt_shl16_done
    ASL __zpR
    ROL __zpR+1
    DEX
    JMP __rt_shl16_loop
__rt_shl16_done:
    RTS
 
__rt_shr16:
    LDX __zpR
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
__rt_shr16_loop:
    CPX #0
    BEQ __rt_shr16_done
    LDA __zpR+1
    CMP #$80
    ROR __zpR+1
    ROR __zpR
    DEX
    JMP __rt_shr16_loop
__rt_shr16_done:
    RTS
 
__rt_topetscii:
    LDA __zpR
    CMP #$61
    BCC __rt_tp_notlower
    CMP #$7B
    BCS __rt_tp_notlower
    SEC
    SBC #$20
    STA __zpR
    JMP __rt_tp_done
__rt_tp_notlower:
    CMP #$41
    BCC __rt_tp_done
    CMP #$5B
    BCS __rt_tp_done
    CLC
    ADC #$80
    STA __zpR
__rt_tp_done:
    RTS
 
__rt_ult16:
    LDA __zpR2+1
    CMP __zpR+1
    BCC __rt_ult16_t
    BNE __rt_ult16_f
    LDA __zpR2
    CMP __zpR
    BCC __rt_ult16_t
__rt_ult16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ult16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_ugt16:
    LDA __zpR+1
    CMP __zpR2+1
    BCC __rt_ugt16_t
    BNE __rt_ugt16_f
    LDA __zpR
    CMP __zpR2
    BCC __rt_ugt16_t
__rt_ugt16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ugt16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_ule16:
    LDA __zpR+1
    CMP __zpR2+1
    BCC __rt_ule16_f
    BNE __rt_ule16_t
    LDA __zpR
    CMP __zpR2
    BCC __rt_ule16_f
__rt_ule16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
__rt_ule16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
 
__rt_uge16:
    LDA __zpR2+1
    CMP __zpR+1
    BCC __rt_uge16_f
    BNE __rt_uge16_t
    LDA __zpR2
    CMP __zpR
    BCC __rt_uge16_f
__rt_uge16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
__rt_uge16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
 
__rt_puts:
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
__rt_puts_loop:
    LDY #0
    LDA (__zpAP),Y
    BEQ __rt_puts_done
    STA __zpR
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    CLC
    LDA __zpAP
    ADC #1
    STA __zpAP
    LDA __zpAP+1
    ADC #0
    STA __zpAP+1
    JMP __rt_puts_loop
__rt_puts_done:
    RTS
 
; ---- global variables --------------------------------------------
__g_garr:
    .fill 10, 0
__g_gcbuf:
    .fill 17, 0
 
; ---- function print_uint ---------------------------------------------
__fn_print_uint_v_n:
    .fill 2, 0
__fn_print_uint_v_buf:
    .fill 6, 0
__fn_print_uint_v_i:
    .fill 2, 0
__fn_print_uint:
    LDA __fn_print_uint_v_n
    STA __zpR
    LDA __fn_print_uint_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_eq16
    LDA __zpR
    ORA __zpR+1
    BNE __L2
    JMP __L0
__L2:
    LDA #<48
    STA __zpR
    LDA #>48
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    RTS
    JMP __L1
__L0:
__L1:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_uint_v_i
    LDA __zpR+1
    STA __fn_print_uint_v_i+1
__L3:
    LDA __fn_print_uint_v_n
    STA __zpR
    LDA __fn_print_uint_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_gt16
    LDA __zpR
    ORA __zpR+1
    BNE __L5
    JMP __L4
__L5:
    LDA __fn_print_uint_v_i
    STA __zpR
    LDA __fn_print_uint_v_i+1
    STA __zpR+1
    CLC
    LDA __zpR
    ADC #<__fn_print_uint_v_buf
    STA __zpAP
    LDA __zpR+1
    ADC #>__fn_print_uint_v_buf
    STA __zpAP+1
    LDA __zpAP
    STA __zpAP2
    LDA __zpAP+1
    STA __zpAP2+1
    LDA __fn_print_uint_v_n
    STA __zpR
    LDA __fn_print_uint_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_sdivmod16
    LDA __zpT0
    STA __zpR
    LDA __zpT0+1
    STA __zpR+1
    LDA __zpAP2
    STA __zpAP
    LDA __zpAP2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA __fn_print_uint_v_n
    STA __zpR
    LDA __fn_print_uint_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_sdivmod16
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_uint_v_n
    LDA __zpR+1
    STA __fn_print_uint_v_n+1
    LDA __fn_print_uint_v_i
    STA __zpR
    LDA __fn_print_uint_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_uint_v_i
    LDA __zpR+1
    STA __fn_print_uint_v_i+1
    JMP __L3
__L4:
__L6:
    LDA __fn_print_uint_v_i
    STA __zpR
    LDA __fn_print_uint_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_gt16
    LDA __zpR
    ORA __zpR+1
    BNE __L8
    JMP __L7
__L8:
    LDA __fn_print_uint_v_i
    STA __zpR
    LDA __fn_print_uint_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    LDA __zpR
    STA __fn_print_uint_v_i
    LDA __zpR+1
    STA __fn_print_uint_v_i+1
    LDA __fn_print_uint_v_i
    STA __zpR
    LDA __fn_print_uint_v_i+1
    STA __zpR+1
    CLC
    LDA __zpR
    ADC #<__fn_print_uint_v_buf
    STA __zpAP
    LDA __zpR+1
    ADC #>__fn_print_uint_v_buf
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_push
    LDA #<48
    STA __zpR
    LDA #>48
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    JMP __L6
__L7:
    RTS
 
; ---- function print_int ---------------------------------------------
__fn_print_int_v_n:
    .fill 2, 0
__fn_print_int:
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_lt16
    LDA __zpR
    ORA __zpR+1
    BNE __L11
    JMP __L9
__L11:
    LDA #<45
    STA __zpR
    LDA #>45
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    SEC
    LDA #0
    SBC __zpR
    TAX
    LDA #0
    SBC __zpR+1
    STA __zpR+1
    STX __zpR
    LDA __zpR
    STA __fn_print_uint_v_n
    LDA __zpR+1
    STA __fn_print_uint_v_n+1
    JSR __fn_print_uint
    JMP __L10
__L9:
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_uint_v_n
    LDA __zpR+1
    STA __fn_print_uint_v_n+1
    JSR __fn_print_uint
__L10:
    RTS
 
; ---- function nl ---------------------------------------------
__fn_nl:
    LDA #<13
    STA __zpR
    LDA #>13
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    RTS
 
; ---- function swap ---------------------------------------------
__fn_swap_v_a:
    .fill 2, 0
__fn_swap_v_b:
    .fill 2, 0
__fn_swap_v_t:
    .fill 2, 0
__fn_swap:
    LDA __fn_swap_v_a
    STA __zpR
    LDA __fn_swap_v_a+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    INY
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __fn_swap_v_t
    LDA __zpR+1
    STA __fn_swap_v_t+1
    LDA __fn_swap_v_a
    STA __zpR
    LDA __fn_swap_v_a+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDA __zpAP
    STA __zpAP2
    LDA __zpAP+1
    STA __zpAP2+1
    LDA __fn_swap_v_b
    STA __zpR
    LDA __fn_swap_v_b+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    INY
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpAP2
    STA __zpAP
    LDA __zpAP2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    INY
    LDA __zpR+1
    STA (__zpAP),Y
    LDA __fn_swap_v_b
    STA __zpR
    LDA __fn_swap_v_b+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDA __zpAP
    STA __zpAP2
    LDA __zpAP+1
    STA __zpAP2+1
    LDA __fn_swap_v_t
    STA __zpR
    LDA __fn_swap_v_t+1
    STA __zpR+1
    LDA __zpAP2
    STA __zpAP
    LDA __zpAP2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    INY
    LDA __zpR+1
    STA (__zpAP),Y
    RTS
 
; ---- function sum_via_ptr ---------------------------------------------
__fn_sum_via_ptr_v_p:
    .fill 2, 0
__fn_sum_via_ptr_v_n:
    .fill 2, 0
__fn_sum_via_ptr_v_total:
    .fill 2, 0
__fn_sum_via_ptr_v_i:
    .fill 2, 0
__fn_sum_via_ptr:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_sum_via_ptr_v_total
    LDA __zpR+1
    STA __fn_sum_via_ptr_v_total+1
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_sum_via_ptr_v_i
    LDA __zpR+1
    STA __fn_sum_via_ptr_v_i+1
__L12:
    LDA __fn_sum_via_ptr_v_i
    STA __zpR
    LDA __fn_sum_via_ptr_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sum_via_ptr_v_n
    STA __zpR
    LDA __fn_sum_via_ptr_v_n+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_lt16
    LDA __zpR
    ORA __zpR+1
    BNE __L15
    JMP __L13
__L15:
    LDA __fn_sum_via_ptr_v_total
    STA __zpR
    LDA __fn_sum_via_ptr_v_total+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sum_via_ptr_v_p
    STA __zpR
    LDA __fn_sum_via_ptr_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    INY
    LDA (__zpAP),Y
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sum_via_ptr_v_total
    LDA __zpR+1
    STA __fn_sum_via_ptr_v_total+1
    LDA __fn_sum_via_ptr_v_p
    STA __zpR
    LDA __fn_sum_via_ptr_v_p+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sum_via_ptr_v_p
    LDA __zpR+1
    STA __fn_sum_via_ptr_v_p+1
__L14:
    LDA __fn_sum_via_ptr_v_i
    STA __zpR
    LDA __fn_sum_via_ptr_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sum_via_ptr_v_i
    LDA __zpR+1
    STA __fn_sum_via_ptr_v_i+1
    JMP __L12
__L13:
    LDA __fn_sum_via_ptr_v_total
    STA __zpR
    LDA __fn_sum_via_ptr_v_total+1
    STA __zpR+1
    RTS
    RTS
 
; ---- function sum_via_ptr_cmp ---------------------------------------------
__fn_sum_via_ptr_cmp_v_p:
    .fill 2, 0
__fn_sum_via_ptr_cmp_v_n:
    .fill 2, 0
__fn_sum_via_ptr_cmp_v_total:
    .fill 2, 0
__fn_sum_via_ptr_cmp_v_end:
    .fill 2, 0
__fn_sum_via_ptr_cmp:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_sum_via_ptr_cmp_v_total
    LDA __zpR+1
    STA __fn_sum_via_ptr_cmp_v_total+1
    LDA __fn_sum_via_ptr_cmp_v_p
    STA __zpR
    LDA __fn_sum_via_ptr_cmp_v_p+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sum_via_ptr_cmp_v_n
    STA __zpR
    LDA __fn_sum_via_ptr_cmp_v_n+1
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sum_via_ptr_cmp_v_end
    LDA __zpR+1
    STA __fn_sum_via_ptr_cmp_v_end+1
__L16:
    LDA __fn_sum_via_ptr_cmp_v_p
    STA __zpR
    LDA __fn_sum_via_ptr_cmp_v_p+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sum_via_ptr_cmp_v_end
    STA __zpR
    LDA __fn_sum_via_ptr_cmp_v_end+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_ult16
    LDA __zpR
    ORA __zpR+1
    BNE __L18
    JMP __L17
__L18:
    LDA __fn_sum_via_ptr_cmp_v_total
    STA __zpR
    LDA __fn_sum_via_ptr_cmp_v_total+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sum_via_ptr_cmp_v_p
    STA __zpR
    LDA __fn_sum_via_ptr_cmp_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    INY
    LDA (__zpAP),Y
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sum_via_ptr_cmp_v_total
    LDA __zpR+1
    STA __fn_sum_via_ptr_cmp_v_total+1
    LDA __fn_sum_via_ptr_cmp_v_p
    STA __zpR
    LDA __fn_sum_via_ptr_cmp_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __zpR2
    LDA __zpR+1
    STA __zpR2+1
    CLC
    LDA __zpR
    ADC #2
    STA __zpR
    LDA __zpR+1
    ADC #0
    STA __zpR+1
    LDA __zpR
    STA __fn_sum_via_ptr_cmp_v_p
    LDA __zpR+1
    STA __fn_sum_via_ptr_cmp_v_p+1
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
    JMP __L16
__L17:
    LDA __fn_sum_via_ptr_cmp_v_total
    STA __zpR
    LDA __fn_sum_via_ptr_cmp_v_total+1
    STA __zpR+1
    RTS
    RTS
 
; ---- function copy_str ---------------------------------------------
__fn_copy_str_v_dst:
    .fill 2, 0
__fn_copy_str_v_src:
    .fill 2, 0
__fn_copy_str_v_n:
    .fill 2, 0
__fn_copy_str:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_copy_str_v_n
    LDA __zpR+1
    STA __fn_copy_str_v_n+1
__L19:
    LDA __fn_copy_str_v_src
    STA __zpR
    LDA __fn_copy_str_v_src+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L21
    JMP __L20
__L21:
    LDA __fn_copy_str_v_dst
    STA __zpR
    LDA __fn_copy_str_v_dst+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDA __zpAP
    STA __zpAP2
    LDA __zpAP+1
    STA __zpAP2+1
    LDA __fn_copy_str_v_src
    STA __zpR
    LDA __fn_copy_str_v_src+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpAP2
    STA __zpAP
    LDA __zpAP2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA __fn_copy_str_v_dst
    STA __zpR
    LDA __fn_copy_str_v_dst+1
    STA __zpR+1
    LDA __zpR
    STA __zpR2
    LDA __zpR+1
    STA __zpR2+1
    CLC
    LDA __zpR
    ADC #1
    STA __zpR
    LDA __zpR+1
    ADC #0
    STA __zpR+1
    LDA __zpR
    STA __fn_copy_str_v_dst
    LDA __zpR+1
    STA __fn_copy_str_v_dst+1
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
    LDA __fn_copy_str_v_src
    STA __zpR
    LDA __fn_copy_str_v_src+1
    STA __zpR+1
    LDA __zpR
    STA __zpR2
    LDA __zpR+1
    STA __zpR2+1
    CLC
    LDA __zpR
    ADC #1
    STA __zpR
    LDA __zpR+1
    ADC #0
    STA __zpR+1
    LDA __zpR
    STA __fn_copy_str_v_src
    LDA __zpR+1
    STA __fn_copy_str_v_src+1
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
    LDA __fn_copy_str_v_n
    STA __zpR
    LDA __fn_copy_str_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_copy_str_v_n
    LDA __zpR+1
    STA __fn_copy_str_v_n+1
    JMP __L19
__L20:
    LDA __fn_copy_str_v_dst
    STA __zpR
    LDA __fn_copy_str_v_dst+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDA __zpAP
    STA __zpAP2
    LDA __zpAP+1
    STA __zpAP2+1
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpAP2
    STA __zpAP
    LDA __zpAP2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA __fn_copy_str_v_n
    STA __zpR
    LDA __fn_copy_str_v_n+1
    STA __zpR+1
    RTS
    RTS
 
; ---- function global_ptr_to_garr0 ---------------------------------------------
__fn_global_ptr_to_garr0:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_garr
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_garr
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    RTS
    RTS
 
; ---- function main ---------------------------------------------
__fn_main_v_x:
    .fill 2, 0
__fn_main_v_p:
    .fill 2, 0
__fn_main_v_a:
    .fill 2, 0
__fn_main_v_b:
    .fill 2, 0
__fn_main_v_s:
    .fill 2, 0
__fn_main_v_i:
    .fill 2, 0
__fn_main:
    LDA #<5
    STA __zpR
    LDA #>5
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_x
    LDA __zpR+1
    STA __fn_main_v_x+1
    LDA #<__fn_main_v_x
    STA __zpR
    LDA #>__fn_main_v_x
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_p
    LDA __zpR+1
    STA __fn_main_v_p+1
    LDA __fn_main_v_p
    STA __zpR
    LDA __fn_main_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    INY
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_nl
    LDA __fn_main_v_p
    STA __zpR
    LDA __fn_main_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDA __zpAP
    STA __zpAP2
    LDA __zpAP+1
    STA __zpAP2+1
    LDA #<42
    STA __zpR
    LDA #>42
    STA __zpR+1
    LDA __zpAP2
    STA __zpAP
    LDA __zpAP2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    INY
    LDA __zpR+1
    STA (__zpAP),Y
    LDA __fn_main_v_x
    STA __zpR
    LDA __fn_main_v_x+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_nl
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_a
    LDA __zpR+1
    STA __fn_main_v_a+1
    LDA #<2
    STA __zpR
    LDA #>2
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_b
    LDA __zpR+1
    STA __fn_main_v_b+1
    LDA #<__fn_main_v_a
    STA __zpR
    LDA #>__fn_main_v_a
    STA __zpR+1
    LDA __zpR
    STA __fn_swap_v_a
    LDA __zpR+1
    STA __fn_swap_v_a+1
    LDA #<__fn_main_v_b
    STA __zpR
    LDA #>__fn_main_v_b
    STA __zpR+1
    LDA __zpR
    STA __fn_swap_v_b
    LDA __zpR+1
    STA __fn_swap_v_b+1
    JSR __fn_swap
    LDA __fn_main_v_a
    STA __zpR
    LDA __fn_main_v_a+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    LDA #<32
    STA __zpR
    LDA #>32
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    LDA __fn_main_v_b
    STA __zpR
    LDA __fn_main_v_b+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_nl
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_i
    LDA __zpR+1
    STA __fn_main_v_i+1
__L22:
    LDA __fn_main_v_i
    STA __zpR
    LDA __fn_main_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<5
    STA __zpR
    LDA #>5
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_lt16
    LDA __zpR
    ORA __zpR+1
    BNE __L25
    JMP __L23
__L25:
    LDA __fn_main_v_i
    STA __zpR
    LDA __fn_main_v_i+1
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_garr
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_garr
    STA __zpAP+1
    LDA __zpAP
    STA __zpAP2
    LDA __zpAP+1
    STA __zpAP2+1
    LDA __fn_main_v_i
    STA __zpR
    LDA __fn_main_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpAP2
    STA __zpAP
    LDA __zpAP2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    INY
    LDA __zpR+1
    STA (__zpAP),Y
__L24:
    LDA __fn_main_v_i
    STA __zpR
    LDA __fn_main_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_i
    LDA __zpR+1
    STA __fn_main_v_i+1
    JMP __L22
__L23:
    LDA #<__g_garr
    STA __zpR
    LDA #>__g_garr
    STA __zpR+1
    LDA __zpR
    STA __fn_sum_via_ptr_v_p
    LDA __zpR+1
    STA __fn_sum_via_ptr_v_p+1
    LDA #<5
    STA __zpR
    LDA #>5
    STA __zpR+1
    LDA __zpR
    STA __fn_sum_via_ptr_v_n
    LDA __zpR+1
    STA __fn_sum_via_ptr_v_n+1
    JSR __fn_sum_via_ptr
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_nl
    LDA #<__g_garr
    STA __zpR
    LDA #>__g_garr
    STA __zpR+1
    LDA __zpR
    STA __fn_sum_via_ptr_cmp_v_p
    LDA __zpR+1
    STA __fn_sum_via_ptr_cmp_v_p+1
    LDA #<5
    STA __zpR
    LDA #>5
    STA __zpR+1
    LDA __zpR
    STA __fn_sum_via_ptr_cmp_v_n
    LDA __zpR+1
    STA __fn_sum_via_ptr_cmp_v_n+1
    JSR __fn_sum_via_ptr_cmp
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_nl
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_garr
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_garr
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_p
    LDA __zpR+1
    STA __fn_main_v_p+1
    LDA __fn_main_v_p
    STA __zpR
    LDA __fn_main_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    INY
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_nl
    LDA __fn_main_v_p
    STA __zpR
    LDA __fn_main_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __zpR2
    LDA __zpR+1
    STA __zpR2+1
    CLC
    LDA __zpR
    ADC #2
    STA __zpR
    LDA __zpR+1
    ADC #0
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_p
    LDA __zpR+1
    STA __fn_main_v_p+1
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
    LDA __fn_main_v_p
    STA __zpR
    LDA __fn_main_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    INY
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_nl
    LDA __fn_main_v_p
    STA __zpR
    LDA __fn_main_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __zpR2
    LDA __zpR+1
    STA __zpR2+1
    SEC
    LDA __zpR
    SBC #2
    STA __zpR
    LDA __zpR+1
    SBC #0
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_p
    LDA __zpR+1
    STA __fn_main_v_p+1
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
    LDA __fn_main_v_p
    STA __zpR
    LDA __fn_main_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __zpR2
    LDA __zpR+1
    STA __zpR2+1
    SEC
    LDA __zpR
    SBC #2
    STA __zpR
    LDA __zpR+1
    SBC #0
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_p
    LDA __zpR+1
    STA __fn_main_v_p+1
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
    LDA __fn_main_v_p
    STA __zpR
    LDA __fn_main_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    INY
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_nl
    LDA #<__g_garr
    STA __zpR
    LDA #>__g_garr
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_p
    LDA __zpR+1
    STA __fn_main_v_p+1
    LDA __fn_main_v_p
    STA __zpR
    LDA __fn_main_v_p+1
    STA __zpR+1
    JSR __rt_push
    LDA #<3
    STA __zpR
    LDA #>3
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_p
    LDA __zpR+1
    STA __fn_main_v_p+1
    LDA __fn_main_v_p
    STA __zpR
    LDA __fn_main_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    INY
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_nl
    LDA __fn_main_v_p
    STA __zpR
    LDA __fn_main_v_p+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    LDA __zpR
    STA __fn_main_v_p
    LDA __zpR+1
    STA __fn_main_v_p+1
    LDA __fn_main_v_p
    STA __zpR
    LDA __fn_main_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    INY
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_nl
    LDA #<4
    STA __zpR
    LDA #>4
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_garr
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_garr
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_garr
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_garr
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    LDA __zpR+1
    CMP #$80
    ROR __zpR+1
    ROR __zpR
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_nl
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_gcbuf
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_gcbuf
    STA __zpAP+1
    LDA __zpAP
    STA __zpAP2
    LDA __zpAP+1
    STA __zpAP2+1
    LDA #<65
    STA __zpR
    LDA #>65
    STA __zpR+1
    LDA __zpAP2
    STA __zpAP
    LDA __zpAP2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_gcbuf
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_gcbuf
    STA __zpAP+1
    LDA __zpAP
    STA __zpAP2
    LDA __zpAP+1
    STA __zpAP2+1
    LDA #<66
    STA __zpR
    LDA #>66
    STA __zpR+1
    LDA __zpAP2
    STA __zpAP
    LDA __zpAP2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA #<2
    STA __zpR
    LDA #>2
    STA __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_gcbuf
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_gcbuf
    STA __zpAP+1
    LDA __zpAP
    STA __zpAP2
    LDA __zpAP+1
    STA __zpAP2+1
    LDA #<67
    STA __zpR
    LDA #>67
    STA __zpR+1
    LDA __zpAP2
    STA __zpAP
    LDA __zpAP2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA #<3
    STA __zpR
    LDA #>3
    STA __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_gcbuf
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_gcbuf
    STA __zpAP+1
    LDA __zpAP
    STA __zpAP2
    LDA __zpAP+1
    STA __zpAP2+1
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpAP2
    STA __zpAP
    LDA __zpAP2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA #<__g_gcbuf
    STA __zpR
    LDA #>__g_gcbuf
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_s
    LDA __zpR+1
    STA __fn_main_v_s+1
    LDA __fn_main_v_s
    STA __zpR
    LDA __fn_main_v_s+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    LDA __fn_main_v_s
    STA __zpR
    LDA __fn_main_v_s+1
    STA __zpR+1
    LDA __zpR
    STA __zpR2
    LDA __zpR+1
    STA __zpR2+1
    CLC
    LDA __zpR
    ADC #1
    STA __zpR
    LDA __zpR+1
    ADC #0
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_s
    LDA __zpR+1
    STA __fn_main_v_s+1
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
    LDA __fn_main_v_s
    STA __zpR
    LDA __fn_main_v_s+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    LDA __fn_main_v_s
    STA __zpR
    LDA __fn_main_v_s+1
    STA __zpR+1
    LDA __zpR
    STA __zpR2
    LDA __zpR+1
    STA __zpR2+1
    CLC
    LDA __zpR
    ADC #1
    STA __zpR
    LDA __zpR+1
    ADC #0
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_s
    LDA __zpR+1
    STA __fn_main_v_s+1
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
    LDA __fn_main_v_s
    STA __zpR
    LDA __fn_main_v_s+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    JSR __fn_nl
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_garr
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_garr
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA #<4
    STA __zpR
    LDA #>4
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_garr
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_garr
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_ult16
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_nl
    LDA #<4
    STA __zpR
    LDA #>4
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_garr
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_garr
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_garr
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_garr
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_ult16
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_nl
    LDA #<2
    STA __zpR
    LDA #>2
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_garr
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_garr
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA #<2
    STA __zpR
    LDA #>2
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_garr
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_garr
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_eq16
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_nl
    LDA #<__str_0
    STA __zpR
    LDA #>__str_0
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_s
    LDA __zpR+1
    STA __fn_main_v_s+1
    LDA #<__g_gcbuf
    STA __zpR
    LDA #>__g_gcbuf
    STA __zpR+1
    LDA __zpR
    STA __fn_copy_str_v_dst
    LDA __zpR+1
    STA __fn_copy_str_v_dst+1
    LDA __fn_main_v_s
    STA __zpR
    LDA __fn_main_v_s+1
    STA __zpR+1
    LDA __zpR
    STA __fn_copy_str_v_src
    LDA __zpR+1
    STA __fn_copy_str_v_src+1
    JSR __fn_copy_str
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_nl
    LDA #<__g_gcbuf
    STA __zpR
    LDA #>__g_gcbuf
    STA __zpR+1
    JSR __rt_puts
    JSR __fn_nl
    LDA __fn_main_v_s
    STA __zpR
    LDA __fn_main_v_s+1
    STA __zpR+1
    JSR __rt_puts
    JSR __fn_nl
    JSR __fn_global_ptr_to_garr0
    LDA __zpR
    STA __fn_main_v_p
    LDA __zpR+1
    STA __fn_main_v_p+1
    LDA __fn_main_v_p
    STA __zpR
    LDA __fn_main_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    INY
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_nl
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_garr
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_garr
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_p
    LDA __zpR+1
    STA __fn_main_v_p+1
    LDA __fn_main_v_p
    STA __zpR
    LDA __fn_main_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDA __zpAP
    STA __zpAP2
    LDA __zpAP+1
    STA __zpAP2+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    INY
    LDA (__zpAP),Y
    STA __zpR+1
    JSR __rt_push
    LDA #<100
    STA __zpR
    LDA #>100
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpAP2
    STA __zpAP
    LDA __zpAP2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    INY
    LDA __zpR+1
    STA (__zpAP),Y
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_garr
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_garr
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    INY
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_nl
    LDA __fn_main_v_p
    STA __zpR
    LDA __fn_main_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    INY
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __zpR2
    LDA __zpR+1
    STA __zpR2+1
    CLC
    LDA __zpR
    ADC #1
    STA __zpR
    LDA __zpR+1
    ADC #0
    STA __zpR+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    INY
    LDA __zpR+1
    STA (__zpAP),Y
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_garr
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_garr
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    INY
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_nl
    LDA #<__str_1
    STA __zpR
    LDA #>__str_1
    STA __zpR+1
    JSR __rt_puts
    RTS
 
; ---- string literals (raw bytes; __rt_puts converts at print time) ----
__str_0:
    .byte 104,101,108,108,111,44,32,112,111,105,110,116,101,114,115,33,0
__str_1:
    .byte 68,79,78,69,46,0
 
; ---- operand stack (128 16-bit slots, indexed by __rt_spidx) -------
__rt_stack:
    .fill 256, 0
